title: "三太郎日記 [1999年〜]"
summary: "日記です．"
topics:
  - "zenn"
  - "markdown"
  - "diary"
published: true
price: 5000 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - "2024_02"
  - "2024_01"
  - "1999_09"
  - "1999_05"
  - "1999_04"
